version: '3.8'
 
services:
  laravel-php:
    container_name: laravel-php
    hostname: laravel-php
    build:
      context: ./
    restart: always
    ports:
      - '2001:80' 
      - '9045:9045'
    volumes: 
      - ./:/var/www/html
      - ./conf.ini:/usr/local/etc/php/conf.d/conf.ini
    networks:
      - laravel   
    stdin_open: true
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    tty: true      
   

##################################################################################  




#################################################################################
#  NETWORKS
#################################################################################
networks:    
  laravel:
    driver: bridge
##################################################################################  


