name: otto_crypt_demo
description: Demo app for OTTO Crypt in Flutter (text + files: photo, docs, audio, video)
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  otto_crypt:
    path: ../otto-crypt-flutter
  file_picker: ^6.1.1
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
